etcd:
  hosts: localhost:2379
service:
  name: nestcloud-starter-service
  port: 3000
  healthCheck:
    ttl: 20
config:
  name: ${{ service.name }}-config
loadbalance:
  rule: RandomRule
  services:
    - name: nestcloud-starter-service
      rule: CustomLoadbalanceRule
proxy:
  routes:
    - id: starter
      uri: lb://${{ service.name }}
      filters:
        - name: CustomProxyFilter
          parameters:
            test-header: test
        - name: ResponseHeaderFilter
          parameters:
            custom-data: hello-world
    - id: github
      uri: https://api.github.com
logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}
